# mitm/gen_provider.py
"""Generate the Layer-2 provider variant from the Layer-1 provider.

The Layer-1 provider (web/public/wallet/provider.js) fetches its backend
with HOST-RELATIVE URLs, which is correct when the page is served from our
own origin (Layer 1: /proxy/<slug>). Under Layer-2 TLS injection the page
is a THIRD-PARTY origin (app.uniswap.org), so a relative fetch would hit
that dapp's origin and 404. This rewrites exactly the three backend fetches
to an absolute proxy base; everything else — uuid, rdns, classify, the
signing rejection — is copied verbatim so the two providers cannot drift in
behavior, only in fetch origin.
"""
import os

# (relative literal, absolute-prefixed replacement builder)
_TARGETS = [
    '"/wallet/read-methods.json"',
    '"/api/wallet/account"',
    '"/api/wallet/rpc"',
]


def generate_l2(source: str, base_url: str) -> str:
    base = base_url.rstrip("/")
    out = source
    for rel in _TARGETS:
        # rel is a quoted literal like "/api/wallet/rpc"; splice base inside the quotes.
        inner = rel[1:-1]                       # /api/wallet/rpc
        absolute = '"' + base + inner + '"'     # "http://host:8081/api/wallet/rpc"
        assert rel in out, f"expected fetch literal {rel} not found in provider source"
        out = out.replace(rel, absolute)
    header = ("// GENERATED by mitm/gen_provider.py from provider.js — do not edit.\n"
              "// Layer-2 variant: backend fetches rewritten to an absolute proxy base\n"
              f"// so injection into a third-party origin still reaches the proxy ({base}).\n")
    return header + out


def main():
    here = os.path.dirname(__file__)
    repo = os.path.dirname(here)
    src = os.path.join(repo, "web", "public", "wallet", "provider.js")
    dst = os.path.join(repo, "web", "public", "wallet", "provider.l2.js")
    base = os.environ.get("WALLET_L2_BASE", "http://192.168.0.1:8081")
    out = generate_l2(open(src).read(), base)
    with open(dst, "w") as f:
        f.write(out)
    print(f"wrote {dst} (base {base})")


if __name__ == "__main__":
    main()
